name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 35.184.253.232 >> ~/.ssh/known_hosts

      - name: Copy Deployment Script
        run: |
          scp -i ~/.ssh/id_rsa deploy.sh shewangzawrobel@35.184.253.232:/home/shewangzawrobel/deploy.sh

      - name: Deploy to GCP Compute Engine
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          ssh -i ~/.ssh/id_rsa shewangzawrobel@35.184.253.232 << 'EOF'
            chmod +x /home/shewangzawrobel/deploy.sh
            DB_HOST=${DB_HOST} DB_PORT=${DB_PORT} DB_USER=${DB_USER} DB_PASS=${DB_PASS} DB_NAME=${DB_NAME} /home/shewangzawrobel/deploy.sh
          EOF
