name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 35.184.253.232 >> ~/.ssh/known_hosts

      - name: Deploy to GCP Compute Engine
        run: |
          ssh -i ~/.ssh/id_rsa shewangzawrobel@35.184.253.232 << 'EOF'
            cd /home/shewangzawrobel/compute-engine-cicd-gcp
            git pull origin main
            npm install
            pm2 restart all
          EOF
